services:
  rijksmuseum-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rijksmuseum-ai-interface
    # Use host network mode for simplicity - no port mapping needed
    network_mode: host
    environment:
      # These values will be overridden by your .env file
      - PORT=${PORT:-3002}
      - HOST=0.0.0.0
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - RIJKSMUSEUM_API_KEY=${RIJKSMUSEUM_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3002}
      - HOSTNAME=${HOSTNAME:-}
      # Use localhost for MCP server URL since we're using host networking
      - MCP_SERVER_URL=http://localhost:${MCP_PORT:-3003}
    restart: unless-stopped
    depends_on:
      - mcp-server
    labels:
      - "com.github.jdhill777.description=Rijksmuseum Art Explorer with Claude AI"
      - "com.github.jdhill777.service=rijksmuseum-interface"

  mcp-server:
    build:
      context: ./rijksmuseum-mcp
      dockerfile: Dockerfile
    container_name: rijksmuseum-ai-mcp-server
    # Use host network mode for simplicity - no port mapping needed
    network_mode: host
    environment:
      - PORT=${MCP_PORT:-3003}
      - RIJKSMUSEUM_API_KEY=${RIJKSMUSEUM_API_KEY}
    volumes:
      # Optional: Mount for logs or other persistent data
      - mcp-data:/app/data
    restart: unless-stopped
    labels:
      - "com.github.jdhill777.description=Rijksmuseum MCP Server"
      - "com.github.jdhill777.service=rijksmuseum-mcp"

volumes:
  mcp-data:
